version: '3'

services:
  database:
    image: mysql:5.7
    container_name: crudmysql_database_container
    ports:
      - "3306:3306"
    networks:
      - crud_net
    volumes:
      - ./database/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crudmysql_web_container
    ports:
      - "3000:3000"
    networks:
      - crud_net
    depends_on:
      - database
    command: sh -c '/usr/src/app/wait-for-it.sh -t 0 database:3306 -- npm start'
    
networks:
  crud_net: